# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: starfactory
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: starfactorytest
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: starfactory_production
  pool: 5
  username: starfactory
  password:
